- TF-IDF로 벡터화한 값은 자카드 유사도를 제외한 유사도 측정에 모두 사용

In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer
sent = ("휴일 인 오늘도 서쪽 을 중심 으로 폭염 이 이어졌는데요, 내일 은 반가운 비 소식 이 있습니다.", "폭염 을 피해서 휴일 에 놀러왔다가 갑작스런 비 로 인해 망연자실 하고 있습니다.")
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(sent)

idf = tfidf_vectorizer.idf_
print(dict(zip(tfidf_vectorizer.get_feature_names(), idf)))

{'갑작스런': 1.4054651081081644, '내일': 1.4054651081081644, '놀러왔다가': 1.4054651081081644, '망연자실': 1.4054651081081644, '반가운': 1.4054651081081644, '서쪽': 1.4054651081081644, '소식': 1.4054651081081644, '오늘도': 1.4054651081081644, '으로': 1.4054651081081644, '이어졌는데요': 1.4054651081081644, '인해': 1.4054651081081644, '있습니다': 1.0, '중심': 1.4054651081081644, '폭염': 1.0, '피해서': 1.4054651081081644, '하고': 1.4054651081081644, '휴일': 1.0}


/Users/stillssi/opt/anaconda3/envs/tf1/lib/python3.8/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


- 코사인 유사도

In [3]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_similarity(tfidf_matrix[0:1], tfidf_matrix[1:2])

array([[0.17952266]])

In [7]:
print(tfidf_matrix[1:2])

  (0, 15)	0.36469322896147516
  (0, 3)	0.36469322896147516
  (0, 10)	0.36469322896147516
  (0, 0)	0.36469322896147516
  (0, 2)	0.36469322896147516
  (0, 14)	0.36469322896147516
  (0, 11)	0.2594822360637418
  (0, 13)	0.2594822360637418
  (0, 16)	0.2594822360637418


- 유클리디언 유사도
    - 거리이기 때문에 값에 제한은 없다: 벡터 일반화-> 다시 유클리디언 유사도 측정(0~1)
    

In [8]:
from sklearn.metrics.pairwise import euclidean_distances

euclidean_distances(tfidf_matrix[0:1], tfidf_matrix[1:2]) #거리

array([[1.28099753]])

In [9]:
import numpy as np

def l1_normalize(v):
    norm=np.sum(v)
    return v/norm

tfidf_norm_l1 = l1_normalize(tfidf_matrix)
euclidean_distances(tfidf_norm_l1[0:1], tfidf_norm_l1[1:2])

array([[0.20491229]])

- 맨해튼 유사도

In [12]:
from sklearn.metrics.pairwise import manhattan_distances

manhattan_distances(tfidf_norm_l1[0:1], tfidf_norm_l1[1:2])

array([[0.77865927]])